### PR TITLE
Add support for Media Foundation, default to latest build version on new W10 bottles

### PR DESCRIPTION
**Pull request by italomandara**
TO DO:
- [x] only copy crossover.inf if d3dmetal installation is enabled
- [x] use d3dmetal (gptk) wording instead of "externals"
- [x] make clearer that GStreamer needs the installation for all users
- [x] grey out GPTK installation option on Ventura

### CODE REVIEW

**Comment by italomandara** [comment]
Beta for testers:
[CXPatcher.app.zip](https://github.com/italomandara/CXPatcher/files/11962542/CXPatcher.app.zip)

**Comment by MysticalOS** [comment]
what does devault to v10 on bottles mean? does it auto configure the windows build number on new bottle installs now so it doesn't need doing after for a lot of games? or something else?

About to test beta right now. gonna go straight to RE2 to test gstreamer patching

**Comment by Gcenx** [comment]
Newly created Win10 bottles will by default report a higher build, this means many games that required a manually step can skip this.

**Comment by MysticalOS** [comment]
Ok that's what I figured. Yeah I just had a habit of just knowing how to auto adjust that automatically but it's smart to upgrade defaults to reduce steps for new setups/users :D

**Comment by Gcenx** [comment]
Yep I’d seen too many users have issues bumping the Win10 build I figured I’d just bump it within the bottle template.

As for Media Foundation, it requires installing the latest official stable gstreamer runtime package for “all users”

**Comment by MysticalOS** [comment]
yeah, the notice in patcher about that is smart, direct download link easy install. already done!

**Comment by Gcenx** [comment]
> yeah, the notice in patcher about that is smart, direct download link easy install. already done! the real question is, will existing bottles work, or only new wine bottles include needed changes to actually use the media foundation?

I never test against existing bottles only new ones so idk I’d it will upgrade or not

**Comment by MysticalOS** [comment]
I tested, it works. RE2 booted right up and played cut scenes with no crash. so A+

**Comment by Gcenx** [comment]
> I tested, it works. RE2 booted right up and played cut scenes with no crash from an existing win10 bottle.. so A+

Existing bottles won’t have there build number upgraded, newly generated Win10 bottles will report a newer build this helps for things like Diablo4

**Comment by MysticalOS** [comment]
Yeah that's to be expected. my bottles are already build upgraded. My test was to make sure the media fix for games like RE2 worked without needing to make a new bottle, it did. :D

**Pull request merged**
