### PR TITLE
Allow changing some constants through UserDefaults

### PR DESCRIPTION
**Pull request by airsquared**
Added `ENABLE_SKIP_VERSION_CHECK_TOGGLE`, `SKIP_DISCLAIMER_CHECK`, and `SKIP_VENTURA_CHECK` to UserDefaults to allow changing these values with

    defaults write com.italomandara.Crossover-patcher ENABLE_SKIP_VERSION_CHECK_TOGGLE true

I doubt random users would change these settings from terminal without understanding what they are, especially since they would be undocumented.

### CODE REVIEW

**Comment by italomandara** [comment]
> I doubt random users would change these settings from terminal without understanding what they are, especially since they would be undocumented.

trust me they will write tutorials and potentially anyone will unlock cxpatcher to do what they're supposed to. 
And we're back to square 1 having tons of support and refund request sent to codeweavers.
@Gcenx what do you think?

**Comment by Gcenx** [comment]
Skipping the version check would be bad, as applying these changes ontop of CX23 will break it.

**Comment by airsquared** [comment]
If I remove the `ENABLE_SKIP_VERSION_CHECK_TOGGLE`, will this be ok to merge?

**Comment by italomandara** [comment]
> If I remove the `ENABLE_SKIP_VERSION_CHECK_TOGGLE`, will this be ok to merge?

The problem is none of the constants are meant for public use, if everybody starts fiddling with them we'll get issues being raised  
for example: X game doesn't work, and then we found out they were using gptk on ventura...
so for the time being me may just leave it.

**Comment by airsquared** [comment]
I see. Then if even `SKIP_DISCLAIMER_CHECK` is not going to be added, you can close the PR.

**Pull request closed without merging**
